language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer
script: jekyll build && htmlproof ./_site

# 브랜치 화이트리스트. GitHub Pages 에서만 사용됨
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # html-proofer 의 설치 속도를 높여줌
