# Site Info
title: AGRAMAR Page
tagline: 'Hello'
description: '우당탕탕'
baseurl: ''
url: 'http://agramar.github.io'
logo: '/public/logo.png'

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: '<!-- more -->'
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: AGRAMAR
  description: AGRAMAR
  gravatar: c5fa24190a425a6101d8411755ffa97c # md5 hash of your email address
  contact:
    github:    https://github.com/agramar
    # email:     http://iamsjh1017@gmail.com/
    # linkedin:  https://www.linkedin.com/in/
    # facebook:  <hide>
    # twitter: <hide>

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/main.jpg
  caption: <br>Hello &copy; <a href="http://agramar.github.io">World</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-104415135-1' # leave blank if you don't want google analytics
disqus_short_name: 'agramar-github-io' # leave blank if you don't want disqus

exclude: [vendor]

