# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Finding The Way Home'
description: "A beautiful narrative written with the world's most elegant publishing platform. The story begins here."

# Author's info
author: 'agramar'
# edit 'categories' in the front matter of every post to match this username
nickname: agramar
bio: '힘듦'
location: 'Seoul, KR'
url: 'http://agramar.github.io/'
image: 'assets/images/casper.png'

short_url: 'agramar.github.io'
google_analytics: UA-104415135-1
disqus: jaehongsong

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'

# Permalinks
permalink: :title
# permalink: author/:username
# permalink: tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: agramar
repo: agramar.github.io
branch: master
relative_source: ../jasper/
destination: ../jasper-pages/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
